### PR TITLE
Add if statement to ensure there is coin in player inventory

### PR DESCRIPTION
**Pull request by omegacoo**
## Description
-Declared variable playerGold and set to zero.
-Checked if there was a coin index in player inventory.
    -If true -> continue normal function by setting playerGold to that quantity.
    -else -> playerGold remains at zero and chat returns insufficient funds warning.

## Related Issue
https://github.com/delaford/game/issues/77

## Motivation and Context
Allows the player to understand why nothing is happening when they are trying to purchase an item.

## How Has This Been Tested?
-I attempted to purchase items from both vendors with no gold in my inventory. This resulted in desired behavior.
-I ensured you could still purchase items when you DO have gold in your inventory (initially this didn't work because I set playerGold as a const, changed to let for expected behavior).
-No changes to other code that I am aware of.

## Types of change
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by omegacoo** [comment]
Wow. Sorry about all the reverts. Had a git meltdown. lol

**Comment by naknode** [comment]
If you could fix the conflicts, that'd be great. I cannot seem to do it via the GitHub UI. Weird. Thank you so much!

**Comment by omegacoo** [comment]
Im not able to see any conflicts.

**Comment by omegacoo** [comment]
Oh I see

**Comment by omegacoo** [comment]
Got it.

**Comment by naknode** [comment]
Thank you! You rock! :-D

**Pull request merged**
