### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by erezvish**
Fixed issue #58 - In-game context menu does not go away even after clicking anywhere else but game

## Description
Used the already existing mechanism of contextmenu:close event. The event was already defined in ContextMenu.vue. Emitted the appropriate event from Delaford.vue and Chatbox.vue to make the context menu close when clicking these areas as well

## Related Issue
#58 
https://github.com/delaford/game/issues/58

## Motivation and Context
Context menu will be closed when left clicking the chatbox or the sidebar

## How Has This Been Tested?
Manual Q&A only

## Types of change

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by erezvish** [comment]
I'm having a bit of problem with signing and gpg, so I'm afraid this one isn'y signed as well

**Comment by naknode** [comment]
Good deal. Thank you -- again!

**Comment by naknode** [comment]
Seems like you are credited https://github.com/delaford/game/graphs/contributors 👍 

In the future, try doing "Fixes #NUMBER" so that GitHub can pickup the issue and automatically close it. It's something they do. Anyway -- thank you again!

**Comment by erezvish** [comment]
Ok, cool. I think I know what happened with the first commit.
I Will commit as you wrote, it's my first time contributing to a project

**Comment by naknode** [comment]
Ah, ok. Glad to know and glad to have you on board! Keep it up.

I'm almost done with Shops in the game. Keep an eye out! :-)

**Comment by erezvish** [comment]
Will do, thanks!

**Pull request merged**
