### PR TITLE
Fixing issue #74 - No skill stats showing in pane & console TypeError

### LINKED ISSUE #74: No skill stats showing in pane & console TypeError
**What is the current behavior?**
1. Console error: 
> TypeError: string.charAt is not a function at VueComponent.capitalizeFirstLetter
2. Stats tab is not showing skills

**If the current behavior is a bug, please provide the exact steps to reproduce.**
1. login into the game (I'm using the guest login)
2. open the console
3. observe the error
*if the error doesn't appear try moving the player around a bit

**What is the expected behavior?**
1. No error
2. When clicking the stats tab in the right pane, observe a list of skills

**Additional context**
This error seems to be due to the behavior of the v-for in Stats.vue . My Vue is a little rusty, but I believe the syntax used is suitable for working with object properties, whereas the stats are received as an array.
This results in capitalizeFirstLetter method getting the number 0 and failing.

To fix the issue, the v-for should probably be on skill in skills and the capitalizeFirstLetter method should receive skill.name
*capitalizeFirstLetter should protect itself by addressing cases where non string input is received is not a string. Alternatively we can replace it with css text-transform: capitalize.

@naknode 
I'm opening new issues for new things I encounter if I'm submitting a pull request shortly after. I think I read somewhere that pull requests will only be accepted for issues, and even if not, I thought it's a good such things documented. Please let me know if you want me to keep doing that or just submit a pull request.

### PR DESCRIPTION
**Pull request by erezvish**
## Description
Fixed #74 - updated the v-for syntax, added _id field to player.json skills and removed the capitalizing method in favor of css text-transform. The skill stats should now show up well and produce no errors in the console.

## Related Issue
https://github.com/delaford/game/issues/74

## Motivation and Context
Stats tab was not showing well,

## How Has This Been Tested?
Manual testing only: click the stats tab and see the skills. open the console and see no errors.

## Screenshots (if appropriate):
image

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Note
I had to use "eslint-disable-line" for two lines in the css of the "skill-name" class. I'm not sure why is this failing the commit script, but it otherwise fails at "npm run lint:css".

### CODE REVIEW

**Comment by naknode** [comment]
I am not getting that error at my latest /master branch run but I have seen it before. This PR really is great because when we remove JS to make it work -- even better.

I am just honestly surprised I forgot all about the `text-transform` property and decided with JS. Heh. Thank.

Great PR.

**Comment by naknode** [comment]
@erezvish I made some small change. What you changed was only for `guest accounts` and real database accounts still had that error. So I decided to use the key of each object and keep using the `text-transform` CSS property. No need for JS like you stipulated -- which is great.

I also removed the `eslint-disable-next` because you forgot to add a space between CSS rules. Not sure how your IDE is but mine tells how I can fix it:

image

Thank you again for your contribution. Hope to see more than just fixes -- but also features! :-)

**Comment by erezvish** [comment]
Sure thing, the capitalize just jogged a memory. I think I was doing that all the time before realizing css already got this covered.
My IDE should be showing problems as well, I just wasn't looking at the problems tab. I'll use that next time, thanks!

Regarding feature development, I'd like to give it a shot. I just want to finish taking a look at something else first and then I should probably start with a small stand alone feature that others are not dependent on. I really enjoy working on this project but I can't know in advance how much time I have to spare, so i don't want clot the development. Any recommendation on what I should be trying to implement?

I should also probably look into setting up an environment with a database sometime in the not so distant future... haha

**Comment by naknode** [comment]
@erezvish Hmm, in terms of feature dev, maybe let's start working on the Quest system and make the first quest? Or maybe we can start adding dialog interaction boxes for some NPCs. The world is your oyster.

As for the discussion, there is a Discord game server we can use for that.

**Comment by erezvish** [comment]
Could the discord invite be expired? I tried to join but it says the invite is invalid

**Comment by naknode** [comment]
@erezvish Try this one https://discordapp.com/invite/nkZnHvD from the main homepage

**Pull request merged**
