### PR TITLE
🏫 Add shops to game 💸

### PR DESCRIPTION
**Pull request by naknode**
## Description

Very excited to finally bring shops to the game! I have been working hard and for a while to bring this online and I think this will bring a lot to the table.

Players will be able to buy/sell their items to an in-game NPC in two different types of shops:

- **General store**: Shop where anything goes and general items. General items do not run out of stock. You can buy/sell anything here.

- **Speciality store**: Buy speciality-related items based on what that person is selling. The first store is Ludovicus's battleaxes in his shop _Ludovicus's Limber Axes_.

By introducing the mechanism of shops, I have thus introduced gold coins as currency and the way for commodities to sell as a facet for quests and other tidbits.

This also brings stackable items to the table! Fishing bait and arrows are first on the list. But I don't want to rush it. With this update, coins are stacks which will have the unique ability be one of the few items whose graphic changes as its quantity grows.

## How Has This Been Tested?

Q&A (manual testing)

## Screenshots (if appropriate):

image

image

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by naknode** [comment]
Nice. So nice. I'll be cleaning anything I missed. I would like to start consolidating some KISS violations (most notably on the Socket class) that spread through-out the `Shop` class and some `Bank`. But I am glad the way this turned out.

**Comment by erezvish** [comment]
Congrats! Looking cool. Great work!

**Comment by naknode** [comment]
Thanks @erezvish! Hoping to see you with some PRs when time permits.

Hoping to implement NPC dialog interaction next... and maybe finally flesh out the map

**Comment by erezvish** [comment]
Will do!
I've been a bit busy lately but will resume as soon as I can

**Pull request merged**
