### PR TITLE
[WIP] Add implementation of woodcutting skill

### PR DESCRIPTION
**Pull request by aleks-rope**
New woodcutting skill that allows player to cut down trees.

## Description
Implementation of woodcutting skill. 
For the skill to be complete it must have the following:

- [x] Allow players to cut down trees.
- [x] Allow player to receive logs from trees.
- [x] Allow player to gain experience from trees.
- [ ] One click chopping (Batched skill).
- [ ] Support at least one other axe. (Optional)
- [ ] Support at least one other tree. (Optional)
- [ ] Add tests!

Please feel free to add/remove anything to the list above.

## Related Issue
There is no open issue/feature for this. This is just something fun I'm implementing for myself. If someday the woodcutting skill becomes necessary please feel free to merge this branch.

## Motivation and Context
It is currently an un-required feature.

## How Has This Been Tested?
N/A

Q&A (manual testing)

## Screenshots (if appropriate):
Players are able to cut down trees and receive logs.

Screen Shot 2020-05-09 at 4 16 10

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by naknode** [comment]
Holy smokes -- this is awesome!

**Comment by aleks-rope** [comment]
> Holy smokes -- this is awesome!

Thanks I'm still not sure wether I should have the woodcutting batched (One click will keep cutting the tree until and return logs until the tree is empty) or have it like the current mining implementation (one click to chop the tree down and get logs). I'll have to play with it and see what makes more sense. If you have a preference please let me know 😄

**Comment by naknode** [comment]
> > Holy smokes -- this is awesome!
> 
> Thanks! I'm still not sure wether I should have the woodcutting batched (One click will keep cutting the tree until and return logs until the tree is empty) or have it like the current mining implementation (one click to chop the tree down and get logs). I'll have to play with it and see what makes more sense. If you have a preference please let me know 😄

I'm thinking the 1st one. Have it return 3-5 logs until it gets "chopped down" and regenerates. Akin to what (Old School) RuneScape does. A lot of this game is based on those mechanics.

(Also don't forget to zoom in into the game. Making the game so small was a mistake...)

**Comment by aleks-rope** [comment]
> I'm thinking the 1st one. Have it return 3-5 logs until it gets "chopped down" and regenerates. Akin to what (Old School) RuneScape does. A lot of this game is based on those mechanics.

Ok! Batched it is! I'll look into the way they do their formulae and try to get it as close as possible.

> I would also argue that there is ONE tree you just can't chop down (the bright green one that acts like a border/fence). Other than that, any tree is game.

Hmm...Perhaps it would be better to specify to the player why the tree cant be chopped down. Like some kind of message when you examine those green trees. For example something like `We shouldn't cut down the forest! `or `This tree doesn't look like it could be cut.`. This way the players don't assume it's a bug since the sprites look so similar. What do you think?

> (Also don't forget to zoom in into the game (CMD / CTRL +). Making the game so small was a mistake...)

I didn't know we could zoom in thanks for the tip!

**Comment by naknode** [comment]
> Ok! Batched it is! I'll look into the way they do their formulae and try to get it as close as possible.

This should not be that difficult. But it can be confusing...

> Hmm...Perhaps it would be better to specify to the player why the tree cant be chopped down. 

Yes, let them know that this kind of tree can't be chopped down. I think the way RuneScape has it... some tree just don't have the Chop option. But I'll look into it.

> I didn't know we could zoom in thanks for the tip!

I am hoping to make some improvements to the UI about this.

---

If you are not doing anything Saturday, I can walk you through some of Delaford and do some pair-programming, if you'd like.

**Comment by aleks-rope** [comment]
I have updated some code and added a screenshot of what it looks like so far. (Excuse the picture of the logs its the best I could do with my limited GIMP knowledge..)

> If you are not doing anything Saturday, I can walk you through some of Delaford and do some pair-programming, if you'd like.
Sure, I can't promise I'll be free but if I'm I'll let you know on discord! 😄

**Comment by naknode** [comment]
@aleks-rope I just a chance to download your branch and play it. Not bad at all. A lot of the same mechanisms from Mining applied so it was pretty much copy/paste at least.

The one bug I saw was that future trees that I cut down did not leave a stump despite getting resources. I'm guessing you're saving that for when you convert it to batches?

Also, the tile for Logs seems off. Not sure where you got your logs from but we try to find our tileset from one simple source of truth so the game feels the same: http://pousse.rapiere.free.fr/tome/tome-tiles.htm

**Comment by aleks-rope** [comment]
> @aleks-rope I just a chance to download your branch and play it. Not bad at all. A lot of the same mechanisms from Mining applied so it was pretty much copy/paste at least.

Thank you. I chose this skill because its close to mining and I wanted to learn how to implement skills and just get in place. Once the batching is in place it will look very different.

> The one bug I saw was that future trees that I cut down did not leave a stump despite getting resources. I'm guessing you're saving that for when you convert it to batches?

Strange, you should be able to see the tree stump. I will take a look and see whats going on.

> Also, the tile for Logs seems off. Not sure where you got your logs from but we try to find our tileset from one simple source of truth so the game feels the same: http://pousse.rapiere.free.fr/tome/tome-tiles.htm

As mentioned previously I whipped it up in GIMP because I couldn't quite find the right tile. This log tile is just temporary placeholder for now for me to visualize. 

Im currently working on batching the chopping process and the axe bonus calculation.

**Comment by naknode** [comment]
> Strange, you should be able to see the tree stump. I will take a look and see whats going on.

I DID see the first stump. The next one I did not.

> As mentioned previously I whipped it up in GIMP because I couldn't quite find the right tile.

Gotcha. Thank you!

**Comment by robbywijaya007** [comment]
...

**Comment by Commensalism1997** [comment]
> ...

what

**Comment by Commensalism1997** [comment]
this is pretty awesome

**Pull request closed without merging**
